name: PostCode API App

on:
  push:
    paths:
      - PostCodesAPI/**

defaults:
  run:
    working-directory: ./PostCodesAPI

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./PostCodesAPI
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore PostCodesAPI.csproj
    - name: Build
      run: dotnet build --no-restore PostCodesAPI.csproj
    - name: Deploy to Lambda
      working-directory: ./PostCodesAPI
      run: dotnet lambda deploy-serverless
